
# knativeChannel holds the name of the Knative channel streaming the device payload
knativeChannel: iot-channel

# knativeEventingNamespace holds the namespace of the Knative eventing installation
knativeEventingNamespace: knative-eventing

image:
  # repository: ghcr.io/drogue-iot

# configuration options for OpenShift routes
routes: {}

ingress:
  enabled: true

loadBalancer:
  enabled: false

# Dependencies

mongodb:
  podSecurityContext:
    enabled: "{{ defaultSecurityContext .Values }}"
  containerSecurityContext:
    enabled: "{{ defaultSecurityContext .Values }}"
  auth:
    rootPassword: admin123456
    enabled: false
