apiVersion: eventing.knative.dev/v1beta1
kind: Broker
metadata:
  name: default
  annotations:
    eventing.knative.dev/broker.class: Kafka
spec:
  config:
    apiVersion: v1
    kind: ConfigMap
    name: kafka-broker-config
