[package]
name = "console-backend"
version = "0.1.0"
authors = ["Jens Reimann <jreimann@redhat.com>"]
edition = "2018"

[dependencies]

console-common = { path = "../console-common" }

actix-web = "3"
actix-cors = "0.4"

log = "0.4"
env_logger = "0.7"

chrono = { version = "0.4", features = ["serde"] }
chrono-tz = "0.5"

anyhow = "1"

serde = "1"
serde_json = "1"

futures = "0.3"

kube = "0.43"
kube-derive = "0.43"
k8s-openapi = { version = "0.9", features = ["v1_17"]}
openshift-openapi = { version = "0.1", features = ["v4_4"] }

async-trait = "0.1"