[package]
name = "drogue-cloud-console-backend"
version = "0.2.0"
authors = ["Jens Reimann <jreimann@redhat.com>"]
edition = "2018"

[dependencies]

drogue-cloud-console-common = { path = "../console-common" }
drogue-cloud-service-common = { path = "../service-common" }

actix = "0.10"
actix-web = "4.0.0-beta.1" # we need v4 as we need tokio 1
actix-cors = "0.6.0-beta.1"
actix-web-httpauth = "0.6.0-beta.1"

openid = "0.8"
url = "2"
reqwest = "0.11"
ring = "0.16.18" # required due to an issue in the public API

pem = "0.8"

log = "0.4"
env_logger = "0.7"
envconfig = "0.9"

chrono = { version = "0.4", features = ["serde"] }
chrono-tz = "0.5"

anyhow = "1"
snafu = "0.6"
failure = "0.1" # required for converting error away from failure

serde = "1"
serde_json = "1"

futures = "0.3"

async-trait = "0.1"

cloudevents-sdk = "0.3"
cloudevents-sdk-rdkafka = "0.3"

uuid = { version = "0.8", features = ["v4"] }

owning_ref = "0.4"

[dependencies.rdkafka]
version = "0.25"
features = ["ssl", "sasl"]