apiVersion: v2
name: drogue-iot
description: |
  Drogue IoT provides serverless IoT cloud
version: 1.0.0
appVersion: 1.0.0
keywords:
  - iot-chart
  - IoT
  - servlerless
home: https://blog.drogue.io/
sources:
  - https://github.com/drogue-iot/drogue-cloud
icon: https://blog.drogue.io/favicon.svg
dependencies:
  - name: postgresql
    version: 9
    repository: https://charts.bitnami.com/bitnami
maintainers:
  - name: dejanb
    email: dbosanac@redhat.com
  - name: ctron
    email: jreimann@redhat.com
  - name: jcrossley3
    email: jcrossle@redhat.com
  - name: jbtrystram
    email: jbtrystram@redhat.com
