[workspace]

members = [
    "endpoint-common",
    "http-endpoint",
    "mqtt-endpoint",
    "ditto-pusher",
    "influxdb-pusher",
    "console-common",
    "console-backend",
    "console-frontend",
]

[patch.crates-io]
#ntex-mqtt = { path = "../ntex-mqtt" }
#patternfly-yew = { path = "../patternfly-yew" }
#drogue-ttn = { path = "../drogue-ttn" }