[workspace]

members = [
    "common",
    "http-endpoint",
    "mqtt-endpoint",
    "influxdb-pusher",
    "console-backend",
    "console-frontend",
]

[patch.crates-io]
#ntex-mqtt = { path = "../ntex-mqtt" }
