apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: grafana-dashboards
    files:
      - dashboards/example.json

resources:
  - config-map.yaml
  - persistent-volume-claim.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml
