apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: http-endpoint
  annotations:
spec:
  template:
    spec:
      containers:
        - image: image-registry.openshift-image-registry.svc:5000/drogue-iot/http-endpoint:latest
          env:
            - name: RUST_LOG
              value: info
            - name: K_SINK
              value: http://event-display
