[package]
name = "drogue-cloud-console-common"
version = "0.6.0"
authors = ["Jens Reimann <jreimann@redhat.com>"]
edition = "2018"

[dependencies]

anyhow = "1"

serde = { version = "1", features = ["derive"] }
