apiVersion: keycloak.org/v1alpha1
kind: KeycloakClient
metadata:
  name: client-services
  labels:
    app.kubernetes.io/part-of: backend
spec:
  realmSelector:
    matchLabels:
      app.kubernetes.io/part-of: console
  client:
    clientId: services
    clientAuthenticatorType: client-secret
    enabled: true
    rootUrl: ""
    publicClient: false
    implicitFlowEnabled: false
    standardFlowEnabled: false
    directAccessGrantsEnabled: false
    serviceAccountsEnabled: true
    fullScopeAllowed: false
    redirectUris: []
    defaultRoles:
      - "service-auth"
      - "service-management"
    protocolMappers:
      - name: add-audience
        protocol: openid-connect
        protocolMapper: oidc-audience-mapper
        consentRequired: false
        config:
          "included.client.audience": "drogue"
          "id.token.claim": "false"
          "access.token.claim": "true"