apiVersion: keycloak.org/v1alpha1
kind: KeycloakClient
metadata:
  name: client-cli
  labels:
    app.kubernetes.io/part-of: backend
spec:
  realmSelector:
    matchLabels:
      app.kubernetes.io/part-of: console
  client:
    clientId: cli
    clientAuthenticatorType: client-secret
    enabled: true
    rootUrl: ""
    publicClient: true
    implicitFlowEnabled: false
    standardFlowEnabled: false
    directAccessGrantsEnabled: true
    serviceAccountsEnabled: false
    fullScopeAllowed: false
    redirectUris: []
    defaultRoles: []
    protocolMappers:
      - name: add-audience
        protocol: openid-connect
        protocolMapper: oidc-audience-mapper
        consentRequired: false
        config:
          "included.client.audience": "drogue"
          "id.token.claim": "false"
          "access.token.claim": "true"