[package]
name = "console-frontend"
version = "0.1.0"
authors = ["Jens Reimann <jreimann@redhat.com>"]
edition = "2018"
description = "Console Frontend"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
anyhow = "1"

console-common = { path = "../console-common" }

yew = "0.17"
yew-router = "0.14"

wasm-bindgen = "0.2"

once_cell = "1"

chrono = { version = "0.4", features = ["wasmbind"] }
chrono-tz = "0.5"

log = "0.4"
wasm-logger = "0.2"

headers = "0.3"

serde = "1"
serde_json = "1"

patternfly-yew = { git = "https://github.com/ctron/patternfly-yew", branch = "main" }

