[package]
name = "web-test"
version = "0.1.0"
authors = ["Jens Reimann <jreimann@redhat.com>"]
edition = "2018"

[dependencies]

actix-rt = "1.1"
actix-service = "1"
actix-web = "3.0.0-beta.3"

serde = { version = "1", features = [ "derive" ] }
serde_json = "1"

env_logger = "0.7"
log = "0.4"
