apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - config-map.yaml
  - persistent-volume-claim.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml
  - pusher-service.yaml
  - subscription.yaml
