[package]
name = "mqtt-endpoint"
version = "0.1.0"
authors = ["Jens Reimann <jreimann@redhat.com>"]
edition = "2018"
license = "Apache-2.0"

[dependencies]

anyhow = "1"

ntex = "0.1.23"
ntex-rt = "0.1.1"
ntex-service = "0.1.3"
ntex-mqtt = "0.3.8"

futures = "0.3"
futures-core = "0.3"
futures-util = "0.3"

reqwest = "0.10"

serde = { version = "1", features = ["derive"] }
serde_json = "1"

uuid = { version = "0.8", features = ["v4"] }

env_logger = "0.7"
log = "0.4"

cloudevents-sdk = "0.3"
cloudevents-sdk-reqwest = "0.3"

drogue-cloud-endpoint-common = { path = "../endpoint-common" }

[dependencies.rust-tls]
version = "0.18.1"
optional = true
package = "rustls"

[features]
default = ["rustls"]
openssl = ["ntex/openssl"]
rustls = ["rust-tls", "ntex/rustls"]
