
global:
  cluster: kubernetes
  domain: .my-cluster.dns
  instance: drogue


endpoints:
  http:
    insecure: false
    ingress:
      # url: <external URL>
  mqtt:
    ingress:
      # host: <external hostname>
      # port: <external port>


integrations:
  mqtt:
    ingress:
      # host: <external hostname>
      # port: <external port>


defaults:
  images:
    repository: ghcr.io/drogue-iot
    pullPolicy: IfNotPresent
    # tag: latest

  passthrough: {}


keycloak:
  adminPassword: admin123456
  identityProviders: []
  postgres:
    # The way postgres gets configured. This can be:
    #  - drogue: Re-use the Drogue Cloud postgres instance
    #  - operator: Let the keycloak operate manage one
    #  - external: Use an external instance
    mode: drogue # reuse drogue instance
    # username: foo
    # password: bar
    # you can provider either:
    #   url: jdbc:postgresql://foo/bar
    # or:
    #   host: postgres
    #   port: 5678
    #   databaseName: keycloak


postgres:
  databaseName: registry
  username: admin
  password: admin123456
  podSecurityContext:
    enabled: false


kafka:
  podSecurityContext:
    enabled: false
