{{- if and .Values.services.console.enabled ( eq .Values.platform "openshift" ) }}
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: console-backend
spec:
  to:
    kind: Service
    name: console-backend
  port:
    targetPort: endpoint
  tls:
    termination: edge
{{- end }}
