kind: Service
apiVersion: v1
metadata:
  name: vorto-converter
  labels:
    app: vorto-converter
spec:
  selector:
    app: vorto-converter
  ports:
    - name: endpoint
      protocol: TCP
      port: 8080
      targetPort: endpoint
