{{- if .Values.sources.mqtt.enabled }}
kind: Service
apiVersion: v1
metadata:
  name: mqtt-endpoint
  labels:
    app: mqtt-endpoint
spec:
  selector:
    app: mqtt-endpoint
  ports:
    - name: endpoint
      protocol: TCP
      port: 443
      targetPort: endpoint
{{- if and ( eq .Values.useLoadBalancer true ) ( ne .Values.platform "openshift" ) }}
  type: LoadBalancer
{{- else }}
  type: NodePort
{{- end }}
{{- end }}
