{{- if .Values.services.influxdb.enabled }}
kind: Service
apiVersion: v1
metadata:
 labels:
   app: influxdb
   app.kubernetes.io/part-of: custom-app-1
 name: influxdb
spec:
 ports:
 - name: api
   port: 8086
   protocol: TCP
   targetPort: 8086
 selector:
   app: influxdb
{{- if and ( eq .Values.useLoadBalancer true ) ( ne .Values.platform "openshift" ) }}
 type: LoadBalancer
{{- else }}
 type: NodePort
{{- end }}
{{- end }}
