{{- if .Values.services.influxdb.enabled }}
apiVersion: messaging.knative.dev/v1
kind: Subscription
metadata:
  name: influxdb-trigger
  labels:
    app.kubernetes.io/part-of: custom-app-1
spec:
  channel:
    apiVersion: messaging.knative.dev/v1alpha1
    kind: KafkaChannel
    name: iot-channel
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: influxdb-pusher
{{- end }}
