apiVersion: sources.knative.dev/v1alpha1
kind: KafkaSource
metadata:
  name: influxdb-kafka-source
  labels:
    app.kubernetes.io/part-of: custom-app-1
spec:
  consumerGroup: influxdb-pusher
  bootstrapServers:
    - kafka-eventing-kafka-bootstrap.knative-eventing.svc:9092
  topics:
    - knative-messaging-kafka.drogue-iot.iot-channel
  sink:
    ref:
      apiVersion: flows.knative.dev/v1
      kind: Sequence
      name: digital-twin
