{{- if .Values.sources.http.enabled }}
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: http-endpoint
  annotations:
spec:
  template:
    metadata:
      labels:
        bindings.knative.dev/include: "true"
    spec:
      containers:
        - image: {{.Values.images.registry}}/{{.Values.images.org}}/http-endpoint:{{.Values.images.tag}}
          env:
            - name: RUST_LOG
              value: info
{{- end }}
