[package]
name = "drogue-cloud-service-common"
version = "0.1.0"
authors = ["Jean-Baptiste Trystram <jbtrystram@redhat.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

#openId
envconfig = "0.9"
openid = "0.7"
log = "0.4"

actix-web = "3"
reqwest = "0.10"

anyhow = "1"

failure = "0.1" # required for converting error away from failure
url = "2"
pem = "0.8"

serde = "1"
serde_json = "1"
snafu = "0.6"
thiserror = "1"

async-trait = "0.1"
futures = "0.3"

kube = "0.47"
kube-derive = "0.47"
k8s-openapi = { version = "0.10", features = ["v1_17"] }
openshift-openapi = { version = "0.2", features = ["v4_4"] }

drogue-cloud-service-api = { path = "../service-api" }
