kind: Service
apiVersion: v1
metadata:
  name: device-management-endpoint
  labels:
    app.kubernetes.io/name: device-management-endpoint
    app.kubernetes.io/part-of: device-registry
spec:
 ports:
 - name: api
   port: 8080
   protocol: TCP
   targetPort: 8080
 selector:
   app.kubernetes.io/name: device-management-endpoint
   app.kubernetes.io/part-of: device-registry
