apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: {{ include "drogue.fullname" . }}-vorto-converter
  labels:
    app.kubernetes.io/name: {{ include "drogue.name" . }}-vorto-converter
{{ include "drogue.labels" . | indent 4 }}
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/scaleToZeroPodRetentionPeriod: "5m"
    spec:
      containers:
        - image: {{ include "drogue.imageRepository" . }}/vorto-converter:0.1.1
          env:
            - name: APIKEY_VORTO
              valueFrom:
                secretKeyRef:
                  name: vorto-api
                  key: token
                  optional: true
          resources:
            requests:
              memory: 128Mi
            limits:
              memory: 128Mi
