apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: {{ include "drogue.fullname" . }}-ditto-pusher
  annotations:
    app.openshift.io/connects-to: '[{"apiVersion":"apps/v1","kind":"Deployment","name":"{{ include "drogue.fullname" . }}-nginx"}]'
  labels:
    app.kubernetes.io/name: {{ include "drogue.name" . }}-ditto-pusher
{{ include "drogue.labels" . | indent 4 }}
spec:
  template:
    spec:
      containers:
        - image: {{ include "drogue.imageRepository" . }}/ditto-pusher:latest
          env:
            - name: RUST_LOG
              value: info
            - name: DITTO_URL
              value: http://{{ include "drogue.fullname" . }}-nginx:8080/ws/2
            - name: DITTO_USERNAME
              value: ditto
            - name: DITTO_PASSWORD
              value: ditto
