apiVersion: flows.knative.dev/v1
kind: Sequence
metadata:
  name: {{ include "drogue.fullname" . }}-digital-twin
  labels:
    app.kubernetes.io/name: {{ include "drogue.name" . }}-digital-twin
{{ include "drogue.labels" . | indent 4 }}
spec:
  channelTemplate:
    apiVersion: messaging.knative.dev/v1alpha1
    kind: KafkaChannel
    spec:
      numPartitions: 1
      replicationFactor: 1
  steps:
    - ref:
        apiVersion: serving.knative.dev/v1
        kind: Service
        name: {{ include "drogue.fullname" . }}-vorto-converter
  reply:
    ref:
      kind: Service
      apiVersion: serving.knative.dev/v1
      name: {{ include "drogue.fullname" . }}-ditto-pusher
