apiVersion: messaging.knative.dev/v1
kind: Subscription
metadata:
  name: digital-twin
  labels:
    app.kubernetes.io/name: digital-twin
    app.kubernetes.io/part-of: digital-twin
{{ include "drogue.labels" . | indent 4 }}
spec:
  channel:
    apiVersion: messaging.knative.dev/v1alpha1
    kind: KafkaChannel
    name: iot-channel
  subscriber:
    ref:
      apiVersion: flows.knative.dev/v1beta1
      kind: Sequence
      name: digital-twin
