{{- if .Values.services.registry.enabled }}
kind: Deployment
apiVersion: apps/v1
metadata:
  name: auth-service
  labels:
    app: auth-service
    app.kubernetes.io/part-of: device-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: endpoint
          image: {{.Values.images.registry}}/{{.Values.images.org}}/authentication-service:{{.Values.images.tag}}
          imagePullPolicy: Always
          env:
            - name: RUST_LOG
              value: info
            - name: BIND_ADDR
              value: "0.0.0.0:8080"
            - name: DATABASE_URL
              value: postgres://user:user1234@drogue-iot-postgresql/postgres
            - name: JWT_ECDSA_SIGNING_KEY
              value: /etc/jwt/jwt.key
          ports:
            - containerPort: 8080
              name: endpoint
              protocol: TCP
          resources:
            limits:
              memory: 64Mi
              cpu: 1
          volumeMounts:
            - mountPath: /etc/jwt
              name: jwt-key
      volumes:
        - name: jwt-key
          secret:
            secretName: jwt-key
{{- end }}
