{{- if .Values.services.registry.enabled }}
kind: Service
apiVersion: v1
metadata:
  name: auth-service
  labels:
    app: auth-service
    app.kubernetes.io/part-of: device-registry
spec:
  selector:
    app: auth-service
  ports:
    - name: endpoint
      protocol: TCP
      port: 8080
      targetPort: endpoint
{{- end }}
