apiVersion: messaging.knative.dev/v1
kind: Subscription
metadata:
  name: outbox-controller
  labels:
    app.kubernetes.io/name: outbox-controller
    app.kubernetes.io/part-of: device-registry
spec:
  channel:
    apiVersion: messaging.knative.dev/v1alpha1
    kind: KafkaChannel
    name: registry
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: outbox-controller