kind: Deployment
apiVersion: apps/v1
metadata:
  name: http-insecure-endpoint
  labels:
    app.kubernetes.io/name: http-insecure-endpoint
    app.kubernetes.io/part-of: endpoints
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: http-insecure-endpoint
      app.kubernetes.io/part-of: endpoints
  template:
    metadata:
      labels:
        app.kubernetes.io/name: http-insecure-endpoint
        app.kubernetes.io/part-of: endpoints
    spec:
      containers:
        - name: endpoint
          image: ghcr.io/drogue-iot/http-endpoint:latest
          imagePullPolicy: Always
          env:
            - name: RUST_LOG
              value: debug
            - name: BIND_ADDR
              value: "0.0.0.0:8080"
            - name: AUTH_SERVICE_URL
              value: http://authentication-service:8080
            - name: DISABLE_TLS
              value: "true"
          ports:
            - containerPort: 8080
              name: endpoint
              protocol: TCP
            - containerPort: 8081
              name: command
              protocol: TCP
          readinessProbe:
            httpGet:
              scheme: HTTP
              port: 8080
              path: /health
