apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: hello
spec:
  steps:
    - name: hello
      image: registry.access.redhat.com/ubi8-minimal
      command:
        - echo
      args:
        - "Hello World!"
