apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-metadata
spec:
  results:
    - name: namespace
      description: The namespace of the build
  steps:
    - name: register-metadata
      image: registry.access.redhat.com/ubi8-minimal
      script: |
        cat /run/secrets/kubernetes.io/serviceaccount/namespace | tee /tekton/results/namespace
