apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-rust-pipeline
spec:

  params:
    - name: repo-url
      type: string
      description: The git repository URL to clone from.
    - name: branch-name
      type: string
      description: The git branch to clone.

  workspaces:
    - name: shared-data

  tasks:

    - name: init
      taskRef:
        name: build-metadata

    - name: checkout
      taskRef:
        name: git-clone
        kind: ClusterTask
      workspaces:
        - name: output
          workspace: shared-data
      params:
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: $(params.branch-name)
        - name: deleteExisting
          value: "true"

    - name: cargo-build
      runAfter: ["checkout"]
      taskRef:
        name: rust-build
      workspaces:
        - name: source
          workspace: shared-data

    - name: container-build
      runAfter: ["cargo-build", "init"]
      taskRef:
        name: buildah
      params:
        - name: DOCKERFILE
          value: web-test/Dockerfile
        - name: IMAGE
          value: "image-registry.openshift-image-registry.svc:5000/$(tasks.init.results.namespace)/web-test:latest"
        - name: TLSVERIFY
          value: "false" # required for now, to push to internal registry
      workspaces:
        - name: source
          workspace: shared-data
