name: rodbot

on:
  issue_comment:
    types: [ "created" ]

jobs:
  rodbot:
    runs-on: ubuntu-20.04

    env:
      GH_TOKEN: ${{ secrets.BOT_PAT }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: ctron/rodbot-action@v0.1.3
        with:
          config: .github/rodbot.yaml
